# Generated by Django 6.0.2 on 2026-02-21 19:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Image')),
                ('is_inventoried', models.BooleanField(default=True, verbose_name='¿Is inventoried?')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('pvp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, verbose_name='Sale price')),
                ('quantity_type', models.CharField(choices=[('unit', 'Unit'), ('kg', 'Kilograms'), ('g', 'Grams'), ('lt', 'Liters'), ('ml', 'Milliliters')], default='unit', max_length=10, verbose_name='Quantity type')),
                ('quantity_value', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity value')),
                ('color', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White')], max_length=20, null=True, verbose_name='Color')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.customercategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
    ]
