# Generated by Django 6.0.2 on 2026-03-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_productcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
