# Generated by Django 6.0.2 on 2026-03-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="average_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Average cost"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_inventoried",
            field=models.BooleanField(default=True, verbose_name="Is inventoried?"),
        ),
    ]
