# Generated by Django 6.0.2 on 2026-04-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_category_delete_customercategory"),
        ("products", "0006_alter_product_options_product_average_cost_and_more"),
        ("sales", "0002_salesorderitem_total_alter_salesorder_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesorder",
            options={},
        ),
        migrations.AlterModelOptions(
            name="salesorderitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="salesorderitem",
            name="total",
        ),
        migrations.AddField(
            model_name="salesorder",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("CONFIRMED", "Confirmed")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
    ]
