# Generated by Django 6.0.2 on 2026-04-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_address_addresstype_addressassignment_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["country", "city", "street"]},
        ),
        migrations.AlterModelOptions(
            name="addressassignment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Address Assignment",
                "verbose_name_plural": "Address Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="addresstype",
            options={
                "ordering": ["name"],
                "verbose_name": "Address Type",
                "verbose_name_plural": "Address Types",
            },
        ),
        migrations.AlterField(
            model_name="addressassignment",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="addresses.address",
            ),
        ),
        migrations.AlterField(
            model_name="addressassignment",
            name="address_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="addresses.addresstype",
            ),
        ),
        migrations.AlterField(
            model_name="addresstype",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="addressassignment",
            unique_together={("content_type", "object_id", "address", "address_type")},
        ),
    ]
