# Generated by Django 6.0.2 on 2026-03-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="is_active",
            new_name="is_postable",
        ),
        migrations.AddField(
            model_name="account",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="accounting.account",
            ),
        ),
    ]
