# Generated by Django 6.0.2 on 2026-03-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_rename_is_active_account_is_postable_account_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["code"],
                "verbose_name": "Account",
                "verbose_name_plural": "Chart of Accounts",
            },
        ),
    ]
