# Generated by Django 6.0.2 on 2026-04-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_alter_account_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={},
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={},
        ),
        migrations.AddField(
            model_name="account",
            name="color",
            field=models.CharField(default="#6c757d", max_length=20),
        ),
        migrations.AddField(
            model_name="account",
            name="icon",
            field=models.CharField(default="fa-regular fa-circle", max_length=50),
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity"),
                    ("INCOME", "Income"),
                    ("EXPENSE", "Expense"),
                ],
                default="ASSET",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="account",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="accounting.account",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="description",
            field=models.CharField(default="ASSET", max_length=255),
            preserve_default=False,
        ),
    ]
