# Generated by Django 6.0.2 on 2026-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["company_name", "last_name", "first_name"]},
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="address",
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
