# Generated by Django 6.0.2 on 2026-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Unit cost"
            ),
        ),
    ]
