# Generated by Django 6.0.2 on 2026-04-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorymovement_unit_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="inventory.inventoryitem",
            ),
        ),
    ]
