# Generated by Django 6.0.2 on 2026-02-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
